name: Delete Workflows

#on: [workflow_dispatch]
on: push

env:
  adbneme: ${secret.DATABRICKS_NAME}

jobs:
  do:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: run simple shell
        run: |
         echo "hello "
         echo " ${{ vars.DATABRICKS_NAME }} "
         
