name: Delete Workflows

on: [workflow_dispatch]

env:
  adbneme: ${secret.DATABRICKS_NAME}

jobs:
  do:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: run simple shell
        run: |
         echo "hello "
         echo " ${secret.DATABRICKS_NAME} "
         
